### ISSUE TITLE
When I run the demo,error occurs as  follows

### ISSUE THREAD

**Issue by X-ray0214** [ADLab-AutoDrive/BEVFusion#13]
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 28, in <module>
    main()
  File "demo/pcd_demo.py", line 20, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/apis/inference.py", line 51, in init_detector
    model = build_detector(config.model, train_cfg=None, test_cfg=config.get('test_cfg'))
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/models/builder.py", line 48, in build_detector
    return DETECTORS.build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mnt/EXOS_AUTO/JIANG_FOLDER/anoconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
TypeError: build_model_from_cfg() got multiple values for argument 'registry'

Who can help me?

**Comment by tingtingliangvs** [comment]
Hi, please uninstall mmdet3d and reinstall in the root directory of this repository.
