### ISSUE TITLE
vis result wrong

### ISSUE THREAD

**Issue by emlfaa** [ADLab-AutoDrive/BEVFusion#67]
hi Thank you for your work！
I want to get visual results with the command:
`python ./tools/misc/visualize_results.py configs/bevfusion/bevf_tf_4x8_6e_nusc.py --result ./work_dirs/bevfusion_tf.pkl --show-dir ./visresult`
but i get a error with this command. Can you help me to see what is the reason? Thanks
`(bevfusion) ub@1:~/workspace/code/github/BEVFusion-main$ python ./tools/misc/visualize_results.py configs/bevfusion/bevf_tf_4x8_6e_nusc.py --result ./work_dirs/bevfusion_tf.pkl --show-dir ./visresult
Traceback (most recent call last):
  File "/home/ub/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'num_views'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/misc/visualize_results.py", line 43, in <module>
    main()
  File "./tools/misc/visualize_results.py", line 31, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/ub/mmdetection3d/mmdet3d/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ub/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuScenesDataset: __init__() got an unexpected keyword argument 'num_views`

**Comment by idealliu** [comment]
Can you tell me how to generate .pkl format, the format I generate is .pth，thanks
